In [1]:
import polars as pl
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import yaml
import indicators as id
CONFIG_PATH = "../config.yaml"

In [2]:
gold = pl.read_parquet("../data/processed/gold_cleaned.parquet")
nifty = pl.read_parquet("../data/processed/nifty_cleaned.parquet")
usdinr = pl.read_parquet("../data/processed/usdinr_cleaned.parquet")
vix = pl.read_parquet("../data/processed/vix_cleaned.parquet")

In [3]:
nifty = id.generate_features(nifty,1.5,0.45)
gold = id.generate_features(gold,1.25,0.5)
usdinr = id.generate_features(usdinr,1.5,0.3)

In [4]:
print(nifty['Date'].to_list() == gold['Date'].to_list() == usdinr['Date'].to_list() == vix['Date'].to_list())

True

In [5]:
nifty.head()

shape: (5, 32)
┌───────────┬───────────┬───────────┬───────────┬───┬───────────┬───────────┬───────────┬──────────┐
│ Close     ┆ High      ┆ Low       ┆ Open      ┆ … ┆ Close_Pos ┆ RSI_Trend ┆ Gap_Intra ┆ Range_Ex │
│ ---       ┆ ---       ┆ ---       ┆ ---       ┆   ┆ _Range    ┆ ---       ┆ day_Convi ┆ pansion  │
│ f64       ┆ f64       ┆ f64       ┆ f64       ┆   ┆ ---       ┆ f64       ┆ nction    ┆ ---      │
│           ┆           ┆           ┆           ┆   ┆ f64       ┆           ┆ ---       ┆ f64      │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆ f64       ┆          │
╞═══════════╪═══════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪══════════╡
│ 4765.2998 ┆ 4773.1000 ┆ 4675.7998 ┆ 4675.7998 ┆ … ┆ 0.919833  ┆ null      ┆ null      ┆ 1.0      │
│ 05        ┆ 98        ┆ 05        ┆ 05        ┆   ┆           ┆           ┆           ┆          │
│ 4749.6499 ┆ 4782.8500 ┆ 4728.8500 ┆ 4774.9501 ┆ … ┆ 0.385182  ┆ null      ┆ -0.000011 ┆ 0.554983 │
│ 02        ┆ 98        ┆ 98        ┆ 95        ┆   ┆           ┆           ┆           ┆          │
│ 4749.9501 ┆ 4779.7998 ┆ 4730.1499 ┆ 4749.0    ┆ … ┆ 0.398798  ┆ null      ┆ -2.7378e- ┆ 0.919443 │
│ 95        ┆ 05        ┆ 02        ┆           ┆   ┆           ┆           ┆ 8         ┆          │
│ 4754.1000 ┆ 4794.8999 ┆ 4686.8500 ┆ 4724.1499 ┆ … ┆ 0.622398  ┆ null      ┆ -0.000034 ┆ 2.176234 │
│ 98        ┆ 02        ┆ 98        ┆ 02        ┆   ┆           ┆           ┆           ┆          │
│ 4742.7998 ┆ 4758.7001 ┆ 4695.4501 ┆ 4747.5498 ┆ … ┆ 0.74861   ┆ null      ┆ 0.000001  ┆ 0.585378 │
│ 05        ┆ 95        ┆ 95        ┆ 05        ┆   ┆           ┆           ┆           ┆          │
└───────────┴───────────┴───────────┴───────────┴───┴───────────┴───────────┴───────────┴──────────┘

In [6]:
# non_buffer_dates = [pl.datetime(2013,12,31),pl.datetime(2026,1,1)]
# nifty = nifty.filter(
#     (pl.col("Date")>non_buffer_dates[0]) & (pl.col("Date")<non_buffer_dates[1])
#     )
# gold = gold.filter(
#     (pl.col("Date")>non_buffer_dates[0]) & (pl.col("Date")<non_buffer_dates[1])
#     )
# usdinr = usdinr.filter(
#     (pl.col("Date")>non_buffer_dates[0]) & (pl.col("Date")<non_buffer_dates[1])
#     )
# vix = vix.filter(
#     (pl.col("Date")>non_buffer_dates[0]) & (pl.col("Date")<non_buffer_dates[1])
#     )

In [7]:
nifty.head()

shape: (5, 32)
┌───────────┬───────────┬───────────┬───────────┬───┬───────────┬───────────┬───────────┬──────────┐
│ Close     ┆ High      ┆ Low       ┆ Open      ┆ … ┆ Close_Pos ┆ RSI_Trend ┆ Gap_Intra ┆ Range_Ex │
│ ---       ┆ ---       ┆ ---       ┆ ---       ┆   ┆ _Range    ┆ ---       ┆ day_Convi ┆ pansion  │
│ f64       ┆ f64       ┆ f64       ┆ f64       ┆   ┆ ---       ┆ f64       ┆ nction    ┆ ---      │
│           ┆           ┆           ┆           ┆   ┆ f64       ┆           ┆ ---       ┆ f64      │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆ f64       ┆          │
╞═══════════╪═══════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪══════════╡
│ 4765.2998 ┆ 4773.1000 ┆ 4675.7998 ┆ 4675.7998 ┆ … ┆ 0.919833  ┆ null      ┆ null      ┆ 1.0      │
│ 05        ┆ 98        ┆ 05        ┆ 05        ┆   ┆           ┆           ┆           ┆          │
│ 4749.6499 ┆ 4782.8500 ┆ 4728.8500 ┆ 4774.9501 ┆ … ┆ 0.385182  ┆ null      ┆ -0.000011 ┆ 0.554983 │
│ 02        ┆ 98        ┆ 98        ┆ 95        ┆   ┆           ┆           ┆           ┆          │
│ 4749.9501 ┆ 4779.7998 ┆ 4730.1499 ┆ 4749.0    ┆ … ┆ 0.398798  ┆ null      ┆ -2.7378e- ┆ 0.919443 │
│ 95        ┆ 05        ┆ 02        ┆           ┆   ┆           ┆           ┆ 8         ┆          │
│ 4754.1000 ┆ 4794.8999 ┆ 4686.8500 ┆ 4724.1499 ┆ … ┆ 0.622398  ┆ null      ┆ -0.000034 ┆ 2.176234 │
│ 98        ┆ 02        ┆ 98        ┆ 02        ┆   ┆           ┆           ┆           ┆          │
│ 4742.7998 ┆ 4758.7001 ┆ 4695.4501 ┆ 4747.5498 ┆ … ┆ 0.74861   ┆ null      ┆ 0.000001  ┆ 0.585378 │
│ 05        ┆ 95        ┆ 95        ┆ 05        ┆   ┆           ┆           ┆           ┆          │
└───────────┴───────────┴───────────┴───────────┴───┴───────────┴───────────┴───────────┴──────────┘

In [8]:
nifty.columns

['Close',
 'High',
 'Low',
 'Open',
 'Date',
 'Ret_1d',
 'Ret_3d',
 'Ret_5d',
 'Ret_20d',
 'Signal',
 'Vol_5d',
 'Vol_20d',
 'FD_Close',
 'TB_Label',
 'Vol Efficiency',
 'Meta_Label',
 'FD_Close_Lag1',
 'MACD_Hist',
 'RSI',
 'ROC_10',
 'Trend_Strength',
 'Gap',
 'Intraday_Return',
 'BB_Pct',
 'ATR_Pct',
 'Vol_Ratio',
 'MA_Ratio',
 'Price_vs_MA20',
 'Close_Pos_Range',
 'RSI_Trend',
 'Gap_Intraday_Convinction',
 'Range_Expansion']

In [9]:
print(nifty['Date'].to_list() == gold['Date'].to_list() == usdinr['Date'].to_list() == vix['Date'].to_list())

True

In [10]:
nifty = nifty.with_columns(
    # Relative strength
    (pl.Series(gold["Ret_5d"]) - pl.col("Ret_5d")).alias("Gold_Nifty_RS_5d"),
    (pl.Series(gold["Ret_20d"]) - pl.col("Ret_20d")).alias("Gold_Nifty_RS_20d"),

    # USDINR features
    pl.Series(usdinr["Ret_3d"]).alias("Usdinr_Ret_3d"),
    pl.Series(usdinr["Ret_5d"]).alias("Usdinr_Ret_5d"),

    pl.when(pl.Series(usdinr["Vol_20d"]) != 0)
    .then(pl.Series(usdinr["Vol_5d"]) / pl.Series(usdinr["Vol_20d"]))
    .otherwise(1)
    .alias("Usdinr_Vol_Ratio"),

    # Momentum alignment
    (
        (pl.col("Ret_5d").sign() == pl.Series(gold["Ret_5d"]).sign())
        .cast(pl.Int8)
    ).alias("Momentum_Align"),

)
nifty = nifty.with_columns(
    # Risk-off flag
    (pl.col("Gold_Nifty_RS_5d") > 0)
    .cast(pl.Int8)
    .alias("Risk_Off"),
    (pl.col("Usdinr_Ret_5d")*pl.col("Momentum_Align"))
    .alias("Usdinr_Stress_Filter")
)

nifty = nifty.with_columns(
    # Risk-off flag
    (pl.col("Gold_Nifty_RS_5d")*pl.col("Ret_5d"))
    .alias("RS_Momentum_Decoupling"),

)

In [11]:
gold = gold.with_columns(
    # Relative strength
    (pl.Series(nifty["Ret_5d"]) - pl.col("Ret_5d")).alias("Nifty_Gold_RS_5d"),

    # USDINR features
    pl.Series(usdinr["Ret_3d"]).alias("Usdinr_Ret_3d"),
    pl.Series(usdinr["Ret_5d"]).alias("Usdinr_Ret_5d"),

    pl.when(pl.Series(usdinr["Vol_20d"]) != 0)
    .then(pl.Series(usdinr["Vol_5d"]) / pl.Series(usdinr["Vol_20d"]))
    .otherwise(1)
    .alias("Usdinr_Vol_Ratio"),

    # Momentum alignment
    (
        (pl.Series(nifty["Ret_5d"]).sign() == pl.col("Ret_5d").sign())
        .cast(pl.Int8)
    ).alias("Momentum_Align"),
)
gold = gold.with_columns(
    # Equity stress flag
    (pl.Series(nifty["Ret_5d"]) < 0)
    .cast(pl.Int8)
    .alias("Equity_Stress"),
    (pl.col("Usdinr_Ret_5d")*pl.col("Momentum_Align"))
    .alias("Usdinr_Stress_Filter"),
)
gold = gold.with_columns(
    (pl.col("Nifty_Gold_RS_5d")*pl.col("Ret_5d"))
    .alias("RS_Momentum_Decoupling"),

)

In [12]:
usdinr = usdinr.with_columns(
    # External returns
    pl.Series(nifty["Ret_5d"]).alias("Nifty_Ret_5d"),
    pl.Series(gold["Ret_5d"]).alias("Gold_Ret_5d"),

    # Nifty volatility ratio
    pl.when(pl.Series(nifty["Vol_20d"]) != 0)
    .then(pl.Series(nifty["Vol_5d"]) / pl.Series(nifty["Vol_20d"]))
    .otherwise(1)
    .alias("Nifty_Vol_Ratio"),
)

usdinr = usdinr.with_columns(
    # Risk-off: gold outperforming equities
    (pl.Series(gold["Ret_5d"]) > pl.Series(nifty["Ret_5d"]))
    .cast(pl.Int8)
    .alias("Risk_Off"),

    # Equity stress: negative equity returns
    (pl.Series(nifty["Ret_5d"]) < 0)
    .cast(pl.Int8)
    .alias("Equity_Stress"),
)

In [13]:
nifty = id.add_vix(nifty,vix)
gold = id.add_vix(gold,vix)
usdinr = id.add_vix(usdinr,vix)

In [14]:
nifty.head()

shape: (5, 46)
┌───────────┬───────────┬───────────┬───────────┬───┬───────────┬───────────┬───────────┬──────────┐
│ Close     ┆ High      ┆ Low       ┆ Open      ┆ … ┆ VIX_Relat ┆ VIX_Shock ┆ VIX_ATR_R ┆ VIX_Mome │
│ ---       ┆ ---       ┆ ---       ┆ ---       ┆   ┆ ive       ┆ ---       ┆ atio      ┆ ntum_Eff │
│ f64       ┆ f64       ┆ f64       ┆ f64       ┆   ┆ ---       ┆ f64       ┆ ---       ┆ iciency  │
│           ┆           ┆           ┆           ┆   ┆ f64       ┆           ┆ f64       ┆ ---      │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ f64      │
╞═══════════╪═══════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪══════════╡
│ 4765.2998 ┆ 4773.1000 ┆ 4675.7998 ┆ 4675.7998 ┆ … ┆ null      ┆ null      ┆ 0.534148  ┆ null     │
│ 05        ┆ 98        ┆ 05        ┆ 05        ┆   ┆           ┆           ┆           ┆          │
│ 4749.6499 ┆ 4782.8500 ┆ 4728.8500 ┆ 4774.9501 ┆ … ┆ null      ┆ 0.009557  ┆ 0.508927  ┆ null     │
│ 02        ┆ 98        ┆ 98        ┆ 95        ┆   ┆           ┆           ┆           ┆          │
│ 4749.9501 ┆ 4779.7998 ┆ 4730.1499 ┆ 4749.0    ┆ … ┆ null      ┆ -0.018932 ┆ 0.468803  ┆ null     │
│ 95        ┆ 05        ┆ 02        ┆           ┆   ┆           ┆           ┆           ┆          │
│ 4754.1000 ┆ 4794.8999 ┆ 4686.8500 ┆ 4724.1499 ┆ … ┆ null      ┆ -0.017368 ┆ 0.476044  ┆ null     │
│ 98        ┆ 02        ┆ 98        ┆ 02        ┆   ┆           ┆           ┆           ┆          │
│ 4742.7998 ┆ 4758.7001 ┆ 4695.4501 ┆ 4747.5498 ┆ … ┆ null      ┆ 0.008641  ┆ 0.462791  ┆ null     │
│ 05        ┆ 95        ┆ 95        ┆ 05        ┆   ┆           ┆           ┆           ┆          │
└───────────┴───────────┴───────────┴───────────┴───┴───────────┴───────────┴───────────┴──────────┘

In [15]:
# Assuming you named your pandas Series 'frac_diff_close'
print(f"Number of NaN values in Nifty: {nifty.null_count().to_numpy().sum()}")
print(f"Number of NaN values in Gold: {gold.null_count().to_numpy().sum()}")
print(f"Number of NaN values in UsdInr: {usdinr.null_count().to_numpy().sum()}")

Number of NaN values in Nifty: 255
Number of NaN values in Gold: 235
Number of NaN values in UsdInr: 222

In [16]:
nifty["Meta_Label"].value_counts()

shape: (2, 2)
┌────────────┬───────┐
│ Meta_Label ┆ count │
│ ---        ┆ ---   │
│ i32        ┆ u32   │
╞════════════╪═══════╡
│ 0          ┆ 2011  │
│ 1          ┆ 1401  │
└────────────┴───────┘

In [17]:
gold["Meta_Label"].value_counts()

shape: (2, 2)
┌────────────┬───────┐
│ Meta_Label ┆ count │
│ ---        ┆ ---   │
│ i32        ┆ u32   │
╞════════════╪═══════╡
│ 1          ┆ 1549  │
│ 0          ┆ 1863  │
└────────────┴───────┘

In [18]:
usdinr["Meta_Label"].value_counts()

shape: (2, 2)
┌────────────┬───────┐
│ Meta_Label ┆ count │
│ ---        ┆ ---   │
│ i32        ┆ u32   │
╞════════════╪═══════╡
│ 0          ┆ 1997  │
│ 1          ┆ 1415  │
└────────────┴───────┘

In [19]:

print(f"Nifty Base Win Rate: {nifty['Meta_Label'].mean():.2%}")
print(f"Gold Base Win Rate: {gold['Meta_Label'].mean():.2%}")
print(f"UsdInr Base Win Rate: {usdinr['Meta_Label'].mean():.2%}")

Nifty Base Win Rate: 41.06%
Gold Base Win Rate: 45.40%
UsdInr Base Win Rate: 41.47%

In [20]:
# How often Signal matched TB_Label, filtering out the "Timeouts" (Label 0)
def calc_directional_win_rate(df):
    # Filter for rows where either the Profit or Stop-Loss was hit
    hits_only = df.filter(pl.col("TB_Label") != 0)
    return hits_only["Meta_Label"].mean()

print(f"Nifty Directional Win Rate: {calc_directional_win_rate(nifty):.2%}")
print(f"Gold Directional Win Rate: {calc_directional_win_rate(gold):.2%}")
print(f"UsdInr Directional Win Rate: {calc_directional_win_rate(usdinr):.2%}")

Nifty Directional Win Rate: 49.33%
Gold Directional Win Rate: 52.05%
UsdInr Directional Win Rate: 51.89%

In [21]:
temporal_split = [
    [pl.datetime(2013,12,31),pl.datetime(2024,1,1)],
    [pl.datetime(2024,2,29),pl.datetime(2026,1,1)]
    ]
nifty_train = nifty.filter(
    (pl.col("Date")>temporal_split[0][0]) & (pl.col("Date")<temporal_split[0][1])
    )
nifty_test = nifty.filter(
    (pl.col("Date")>temporal_split[1][0]) & (pl.col("Date")<temporal_split[1][1])
    )

gold_train = gold.filter(
    (pl.col("Date")>temporal_split[0][0]) & (pl.col("Date")<temporal_split[0][1])
    )
gold_test = gold.filter(
    (pl.col("Date")>temporal_split[1][0]) & (pl.col("Date")<temporal_split[1][1])
    )
usdinr_train = usdinr.filter(
    (pl.col("Date")>temporal_split[0][0]) & (pl.col("Date")<temporal_split[0][1])
    )
usdinr_test = usdinr.filter(
    (pl.col("Date")>temporal_split[1][0]) & (pl.col("Date")<temporal_split[1][1])
    )

In [23]:
# Assuming you named your pandas Series 'frac_diff_close'
print(f"Number of NaN values in Nifty: {nifty_train.null_count().to_numpy().sum()}")
print(f"Number of NaN values in Gold: {gold_train.null_count().to_numpy().sum()}")
print(f"Number of NaN values in UsdInr: {usdinr_train.null_count().to_numpy().sum()}")

Number of NaN values in Nifty: 0
Number of NaN values in Gold: 0
Number of NaN values in UsdInr: 0

In [25]:
nifty_train.columns

['Close',
 'High',
 'Low',
 'Open',
 'Date',
 'Ret_1d',
 'Ret_3d',
 'Ret_5d',
 'Ret_20d',
 'Signal',
 'Vol_5d',
 'Vol_20d',
 'FD_Close',
 'TB_Label',
 'Vol Efficiency',
 'Meta_Label',
 'FD_Close_Lag1',
 'MACD_Hist',
 'RSI',
 'ROC_10',
 'Trend_Strength',
 'Gap',
 'Intraday_Return',
 'BB_Pct',
 'ATR_Pct',
 'Vol_Ratio',
 'MA_Ratio',
 'Price_vs_MA20',
 'Close_Pos_Range',
 'RSI_Trend',
 'Gap_Intraday_Convinction',
 'Range_Expansion',
 'Gold_Nifty_RS_5d',
 'Gold_Nifty_RS_20d',
 'Usdinr_Ret_3d',
 'Usdinr_Ret_5d',
 'Usdinr_Vol_Ratio',
 'Momentum_Align',
 'Risk_Off',
 'Usdinr_Stress_Filter',
 'RS_Momentum_Decoupling',
 'VIX',
 'VIX_Relative',
 'VIX_Shock',
 'VIX_ATR_Ratio',
 'VIX_Momentum_Efficiency']

In [22]:
nifty_train.write_parquet("../data/processed/train/nifty.parquet")
gold_train.write_parquet("../data/processed/train/gold.parquet")
usdinr_train.write_parquet("../data/processed/train/usdinr.parquet")
nifty_test.write_parquet("../data/processed/test/nifty.parquet")
gold_test.write_parquet("../data/processed/test/gold.parquet")
usdinr_test.write_parquet("../data/processed/test/usdinr.parquet")

In [23]:
nifty.shape

(3412, 46)