In [1]:
import polars as pl
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import yaml
import feature_eng as fe
CONFIG_PATH = "../config.yaml"

In [2]:
gold = pl.read_parquet("../data/processed/gold_cleaned.parquet")
nifty = pl.read_parquet("../data/processed/nifty_cleaned.parquet")
usdinr = pl.read_parquet("../data/processed/usdinr_cleaned.parquet")

In [3]:
nifty = fe.generate_features(nifty,1.5,0.45)
gold = fe.generate_features(gold,1.75,0.5)
usdinr = fe.generate_features(usdinr,1.5,0.3)

In [4]:
print(nifty["Date"].to_list() == gold["Date"].to_list() == usdinr["Date"].to_list())

True

In [5]:
nifty.head()

shape: (5, 27)
┌───────────┬───────────┬───────────┬───────────┬───┬───────────┬───────────┬───────────┬──────────┐
│ Close     ┆ High      ┆ Low       ┆ Open      ┆ … ┆ Price_vs_ ┆ Close_Pos ┆ Intraday_ ┆ Range_Ex │
│ ---       ┆ ---       ┆ ---       ┆ ---       ┆   ┆ MA20      ┆ _Range    ┆ Return    ┆ pansion  │
│ f64       ┆ f64       ┆ f64       ┆ f64       ┆   ┆ ---       ┆ ---       ┆ ---       ┆ ---      │
│           ┆           ┆           ┆           ┆   ┆ f64       ┆ f64       ┆ f64       ┆ f64      │
╞═══════════╪═══════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪══════════╡
│ 4765.2998 ┆ 4773.1000 ┆ 4675.7998 ┆ 4675.7998 ┆ … ┆ null      ┆ 0.919833  ┆ 0.019141  ┆ 1.0      │
│ 05        ┆ 98        ┆ 05        ┆ 05        ┆   ┆           ┆           ┆           ┆          │
│ 4749.6499 ┆ 4782.8500 ┆ 4728.8500 ┆ 4774.9501 ┆ … ┆ null      ┆ 0.385182  ┆ -0.005299 ┆ 0.554983 │
│ 02        ┆ 98        ┆ 98        ┆ 95        ┆   ┆           ┆           ┆           ┆          │
│ 4749.9501 ┆ 4779.7998 ┆ 4730.1499 ┆ 4749.0    ┆ … ┆ null      ┆ 0.398798  ┆ 0.0002    ┆ 0.919443 │
│ 95        ┆ 05        ┆ 02        ┆           ┆   ┆           ┆           ┆           ┆          │
│ 4754.1000 ┆ 4794.8999 ┆ 4686.8500 ┆ 4724.1499 ┆ … ┆ null      ┆ 0.622398  ┆ 0.00634   ┆ 2.176234 │
│ 98        ┆ 02        ┆ 98        ┆ 02        ┆   ┆           ┆           ┆           ┆          │
│ 4742.7998 ┆ 4758.7001 ┆ 4695.4501 ┆ 4747.5498 ┆ … ┆ null      ┆ 0.74861   ┆ -0.001001 ┆ 0.585378 │
│ 05        ┆ 95        ┆ 95        ┆ 05        ┆   ┆           ┆           ┆           ┆          │
└───────────┴───────────┴───────────┴───────────┴───┴───────────┴───────────┴───────────┴──────────┘

In [6]:
non_buffer_dates = [pl.datetime(2013,12,31),pl.datetime(2026,1,1)]
nifty = nifty.filter(
    (pl.col("Date")>non_buffer_dates[0]) & (pl.col("Date")<non_buffer_dates[1])
    )
gold = gold.filter(
    (pl.col("Date")>non_buffer_dates[0]) & (pl.col("Date")<non_buffer_dates[1])
    )
usdinr = usdinr.filter(
    (pl.col("Date")>non_buffer_dates[0]) & (pl.col("Date")<non_buffer_dates[1])
    )

In [7]:
nifty.head()

shape: (5, 27)
┌───────────┬───────────┬───────────┬───────────┬───┬───────────┬───────────┬───────────┬──────────┐
│ Close     ┆ High      ┆ Low       ┆ Open      ┆ … ┆ Price_vs_ ┆ Close_Pos ┆ Intraday_ ┆ Range_Ex │
│ ---       ┆ ---       ┆ ---       ┆ ---       ┆   ┆ MA20      ┆ _Range    ┆ Return    ┆ pansion  │
│ f64       ┆ f64       ┆ f64       ┆ f64       ┆   ┆ ---       ┆ ---       ┆ ---       ┆ ---      │
│           ┆           ┆           ┆           ┆   ┆ f64       ┆ f64       ┆ f64       ┆ f64      │
╞═══════════╪═══════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪══════════╡
│ 6221.1499 ┆ 6358.2998 ┆ 6211.2998 ┆ 6301.25   ┆ … ┆ 0.995498  ┆ 0.067007  ┆ -0.012712 ┆ 4.9      │
│ 02        ┆ 05        ┆ 05        ┆           ┆   ┆           ┆           ┆           ┆          │
│ 6211.1499 ┆ 6221.7001 ┆ 6171.25   ┆ 6194.5498 ┆ … ┆ 0.993499  ┆ 0.790877  ┆ 0.00268   ┆ 0.343199 │
│ 02        ┆ 95        ┆           ┆ 05        ┆   ┆           ┆           ┆           ┆          │
│ 6191.4501 ┆ 6224.7001 ┆ 6170.25   ┆ 6220.8500 ┆ … ┆ 0.990741  ┆ 0.38935   ┆ -0.004726 ┆ 1.079286 │
│ 95        ┆ 95        ┆           ┆ 98        ┆   ┆           ┆           ┆           ┆          │
│ 6162.25   ┆ 6221.5    ┆ 6144.75   ┆ 6203.8999 ┆ … ┆ 0.986839  ┆ 0.228013  ┆ -0.006714 ┆ 1.409545 │
│           ┆           ┆           ┆ 02        ┆   ┆           ┆           ┆           ┆          │
│ 6174.6000 ┆ 6192.1000 ┆ 6160.3500 ┆ 6178.0498 ┆ … ┆ 0.990318  ┆ 0.448819  ┆ -0.000558 ┆ 0.413681 │
│ 98        ┆ 98        ┆ 98        ┆ 05        ┆   ┆           ┆           ┆           ┆          │
└───────────┴───────────┴───────────┴───────────┴───┴───────────┴───────────┴───────────┴──────────┘

In [8]:
nifty.columns

['Close',
 'High',
 'Low',
 'Open',
 'Date',
 'Ret_1d',
 'Ret_3d',
 'Ret_5d',
 'Ret_20d',
 'Vol_5d',
 'Vol_20d',
 'FD_Close',
 'Label',
 'FD_Close_Lag1',
 'MACD_Hist',
 'RSI',
 'ROC_10',
 'Trend_Strength',
 'Gap',
 'BB_Pct',
 'ATR_Pct',
 'Vol_Ratio',
 'MA_Ratio',
 'Price_vs_MA20',
 'Close_Pos_Range',
 'Intraday_Return',
 'Range_Expansion']

In [9]:
print(nifty["Date"].to_list() == gold["Date"].to_list() == usdinr["Date"].to_list())

True

In [10]:
nifty = nifty.with_columns(
    # Relative strength
    (pl.Series(gold["Ret_5d"]) - pl.col("Ret_5d")).alias("Gold_Nifty_RS_5d"),
    (pl.Series(gold["Ret_20d"]) - pl.col("Ret_20d")).alias("Gold_Nifty_RS_20d"),

    # USDINR features
    pl.Series(usdinr["Ret_3d"]).alias("Usdinr_Ret_3d"),
    pl.Series(usdinr["Ret_5d"]).alias("Usdinr_Ret_5d"),

    pl.when(pl.Series(usdinr["Vol_20d"]) != 0)
    .then(pl.Series(usdinr["Vol_5d"]) / pl.Series(usdinr["Vol_20d"]))
    .otherwise(1)
    .alias("Usdinr_Vol_Ratio"),

    # Momentum alignment
    (
        (pl.col("Ret_5d").sign() == pl.Series(gold["Ret_5d"]).sign())
        .cast(pl.Int8)
    ).alias("Momentum_Align"),

)
nifty = nifty.with_columns(
    # Risk-off flag
    (pl.col("Gold_Nifty_RS_5d") > 0)
    .cast(pl.Int8)
    .alias("Risk_Off"),
)

In [11]:
gold = gold.with_columns(
    # Relative strength
    (pl.Series(nifty["Ret_5d"]) - pl.col("Ret_5d")).alias("Nifty_Gold_RS_5d"),

    # USDINR features
    pl.Series(usdinr["Ret_3d"]).alias("Usdinr_Ret_3d"),
    pl.Series(usdinr["Ret_5d"]).alias("Usdinr_Ret_5d"),

    pl.when(pl.Series(usdinr["Vol_20d"]) != 0)
    .then(pl.Series(usdinr["Vol_5d"]) / pl.Series(usdinr["Vol_20d"]))
    .otherwise(1)
    .alias("Usdinr_Vol_Ratio"),

    # Momentum alignment
    (
        (pl.Series(nifty["Ret_5d"]).sign() == pl.col("Ret_5d").sign())
        .cast(pl.Int8)
    ).alias("Momentum_Align"),
)
gold = gold.with_columns(
    # Equity stress flag
    (pl.Series(nifty["Ret_5d"]) < 0)
    .cast(pl.Int8)
    .alias("Equity_Stress"),
)

In [12]:
usdinr = usdinr.with_columns(
    # External returns
    pl.Series(nifty["Ret_5d"]).alias("Nifty_Ret_5d"),
    pl.Series(gold["Ret_5d"]).alias("Gold_Ret_5d"),

    # Nifty volatility ratio
    pl.when(pl.Series(nifty["Vol_20d"]) != 0)
    .then(pl.Series(nifty["Vol_5d"]) / pl.Series(nifty["Vol_20d"]))
    .otherwise(1)
    .alias("Nifty_Vol_Ratio"),
)

usdinr = usdinr.with_columns(
    # Risk-off: gold outperforming equities
    (pl.Series(gold["Ret_5d"]) > pl.Series(nifty["Ret_5d"]))
    .cast(pl.Int8)
    .alias("Risk_Off"),

    # Equity stress: negative equity returns
    (pl.Series(nifty["Ret_5d"]) < 0)
    .cast(pl.Int8)
    .alias("Equity_Stress"),
)

In [13]:
nifty.head()

shape: (5, 34)
┌───────────┬───────────┬───────────┬───────────┬───┬───────────┬───────────┬───────────┬──────────┐
│ Close     ┆ High      ┆ Low       ┆ Open      ┆ … ┆ Usdinr_Re ┆ Usdinr_Vo ┆ Momentum_ ┆ Risk_Off │
│ ---       ┆ ---       ┆ ---       ┆ ---       ┆   ┆ t_5d      ┆ l_Ratio   ┆ Align     ┆ ---      │
│ f64       ┆ f64       ┆ f64       ┆ f64       ┆   ┆ ---       ┆ ---       ┆ ---       ┆ i8       │
│           ┆           ┆           ┆           ┆   ┆ f64       ┆ f64       ┆ i8        ┆          │
╞═══════════╪═══════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪══════════╡
│ 6221.1499 ┆ 6358.2998 ┆ 6211.2998 ┆ 6301.25   ┆ … ┆ 0.0       ┆ 0.408289  ┆ 1         ┆ 1        │
│ 02        ┆ 05        ┆ 05        ┆           ┆   ┆           ┆           ┆           ┆          │
│ 6211.1499 ┆ 6221.7001 ┆ 6171.25   ┆ 6194.5498 ┆ … ┆ 0.00437   ┆ 0.478696  ┆ 0         ┆ 1        │
│ 02        ┆ 95        ┆           ┆ 05        ┆   ┆           ┆           ┆           ┆          │
│ 6191.4501 ┆ 6224.7001 ┆ 6170.25   ┆ 6220.8500 ┆ … ┆ 0.005494  ┆ 0.554891  ┆ 0         ┆ 1        │
│ 95        ┆ 95        ┆           ┆ 98        ┆   ┆           ┆           ┆           ┆          │
│ 6162.25   ┆ 6221.5    ┆ 6144.75   ┆ 6203.8999 ┆ … ┆ 0.010378  ┆ 0.214608  ┆ 0         ┆ 1        │
│           ┆           ┆           ┆ 02        ┆   ┆           ┆           ┆           ┆          │
│ 6174.6000 ┆ 6192.1000 ┆ 6160.3500 ┆ 6178.0498 ┆ … ┆ 0.004856  ┆ 0.590477  ┆ 0         ┆ 1        │
│ 98        ┆ 98        ┆ 98        ┆ 05        ┆   ┆           ┆           ┆           ┆          │
└───────────┴───────────┴───────────┴───────────┴───┴───────────┴───────────┴───────────┴──────────┘

In [14]:
# Assuming you named your pandas Series 'frac_diff_close'
print(f"Number of NaN values in Nifty: {nifty.null_count().to_numpy().sum()}")
print(f"Number of NaN values in Gold: {gold.null_count().to_numpy().sum()}")
print(f"Number of NaN values in UsdInr: {usdinr.null_count().to_numpy().sum()}")

Number of NaN values in Nifty: 0
Number of NaN values in Gold: 0
Number of NaN values in UsdInr: 0

In [15]:
nifty["Label"].value_counts()

shape: (3, 2)
┌───────┬───────┐
│ Label ┆ count │
│ ---   ┆ ---   │
│ i64   ┆ u32   │
╞═══════╪═══════╡
│ 0     ┆ 1018  │
│ 1     ┆ 886   │
│ -1    ┆ 1035  │
└───────┴───────┘

In [16]:
temporal_split = [
    [pl.datetime(2013,12,31),pl.datetime(2024,1,1)],
    [pl.datetime(2024,2,29),pl.datetime(2026,1,1)]
    ]
nifty_train = nifty.filter(
    (pl.col("Date")>temporal_split[0][0]) & (pl.col("Date")<temporal_split[0][1])
    )
nifty_test = nifty.filter(
    (pl.col("Date")>temporal_split[1][0]) & (pl.col("Date")<temporal_split[1][1])
    )

gold_train = gold.filter(
    (pl.col("Date")>temporal_split[0][0]) & (pl.col("Date")<temporal_split[0][1])
    )
gold_test = gold.filter(
    (pl.col("Date")>temporal_split[1][0]) & (pl.col("Date")<temporal_split[1][1])
    )
usdinr_train = usdinr.filter(
    (pl.col("Date")>temporal_split[0][0]) & (pl.col("Date")<temporal_split[0][1])
    )
usdinr_test = usdinr.filter(
    (pl.col("Date")>temporal_split[1][0]) & (pl.col("Date")<temporal_split[1][1])
    )

In [17]:
nifty_train.write_parquet("../data/processed/train/nifty.parquet")
gold_train.write_parquet("../data/processed/train/gold.parquet")
usdinr_train.write_parquet("../data/processed/train/usdinr.parquet")
nifty_test.write_parquet("../data/processed/test/nifty.parquet")
gold_test.write_parquet("../data/processed/test/gold.parquet")
usdinr_test.write_parquet("../data/processed/test/usdinr.parquet")

In [18]:
nifty.shape

(2939, 34)